[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  SANITY_STUDIO_PROJECT_ID = "rksihl2j"
  SANITY_STUDIO_DATASET = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 